name: Run unit tests

on:
  push:
    branches:
      - 'main'
    pull_request:
      branches:
        - '**'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: ./homework09
        run:  npm install
      - name: Run Integration Test
        working-directory: ./homework09
        run: npm run test